config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  resources :posts do
    resources :comments, only: :create
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
  resources :tags, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :tags_posts
  has_many :tags, through: :tags_posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user

  validates :title, :content, presence: true

  def self.search(search)
    return Post.all unless search
    Post.where('title LIKE(?)', "#{search}%")
  end


  def liked_by?(user_id)
    likes.find_by(user_id: user_id)
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tags_posts, dependent: :destroy
  has_many :posts, through: :tags_posts
end

app/models/tags_post.rb
class TagsPost < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :posts
  has_many :comments
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post, only: [:create, :destroy]

  def create
    @like = current_user.likes.create(post_id: params[:post_id], user_id: current_user.id)
  end 

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
  end

  private
  def like_params
    params.permit(post_id: params[:post_id], user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
    
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @post = Post.includes(:user).order("created_at DESC").page(params[:page]).per(5)
    @tag = Tag.includes(:posts)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to root_path
    else 
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
    @like= Like.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to root_path
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def search
    @post = Post.search(params[:keyword]).order("created_at DESC").page(params[:page]).per(5)
    @tag = Tag.includes(:posts)
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :tag_ids).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

  def set_tag
    @tag = Tag.find(params[:tag_id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.includes(:posts)
    tag = Tag.find(params[:id])
    @tag_name = tag.name
    @post = tag.posts.includes(:user).order("created_at DESC").page(params[:page]).per(5)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @post = user.posts.includes(:user).order("created_at DESC").page(params[:page]).per(5)
    @tag = Tag.includes(:posts)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Our wisdom bag
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/likes/_like.html.haml
- if user_signed_in?
  - if current_user && @post.liked_by?(current_user.id)
    %span
      = link_to post_like_path(@post.liked_by?(current_user.id), post_id: @post.id), class:"showform__like__btndelete", id:"likebtn", method: :delete, remote: true do
        = icon('far', 'thumbs-up')
        = @post.likes.count
  - else
    %span
      = link_to post_likes_path(@post), class:"showform__like__btn", id:"likebtn", method: :post, remote: true do
        = icon('far', 'thumbs-up')
        = @post.likes.count

app/views/likes/create.js.erb
$('#like').html("<%= j(render partial: 'likes/like', locals: { post: @post}) %>");

app/views/likes/destroy.js.erb
$('#like').html("<%= j(render partial: 'likes/like', locals: { post: @post}) %>");

app/views/posts/_post.html.haml
.content__box__main__articlebox
  .content__box__main__articlebox__titlebox
    = link_to post_path(post.id), class:"content__box__main__articlebox__titlebox__title" do
      = post.title
  .content__box__main__articlebox__timebox
    .content__box__main__articlebox__timebox__time
      = post.created_at.strftime("%Y年%m月%d日 %H時%M分")
    .content__box__main__articlebox__timebox__good
      = "いいね:"
      = post.likes.count
  .content__box__main__articlebox__tag
    - post.tags.each do |tag|
      = tag.name
  .content__box__main__articlebox__tag
    = "コメント："
    = post.comments.count

app/views/posts/edit.html.haml
.wrapper
  = render "shared/header"
  .content
    .content__box
      .form
        %h1.form__font
          = "編集する"
          = render "shared/form"

app/views/posts/index.html.haml
.wrapper
  = render "shared/header"
  .content
    .content__box
      = render "shared/side"
      = render "shared/main"

app/views/posts/new.html.haml
.wrapper
  = render "shared/header"
  .content
    .content__box
      .form
        %h1.form__font
          = "投稿する"
          = render "shared/form"

app/views/posts/search.html.haml
.wrapper
  = render "shared/header"
  .content
    .content__box
      = render "shared/side"
      = render "shared/main"

app/views/posts/show.html.haml
.wrapper
  = render "shared/header"
  .content
    .content__box
      .showform
        .showform__userbox
          .showform__userbox__user
            = @post.user.nickname + "さんの記事"
        .showform__box
          - if user_signed_in? && current_user.id == @post.user_id 
            .showform__box__editbox
              = link_to "編集", "/posts/#{@post.id}/edit", class: "showform__box__editbox__edit", method: :get
            .showform__box__deletebox
              = link_to "削除", "#", class: "showform__box__deletebox__delete", method: :delete
        %span
          .showform__like{ "id": "like"}
            = render partial: "likes/like", loacals: { post: @post, like: @like, likes: @likes }
        .showform__titlebox
          .showform__titlebox__title
            = @post.title
        .showform__tagbox
          .showform__tagbox__tag
            - @post.tags.each do |tag|
              = tag.name
        .showform__contentbox
          .showform__contentbox__content
            = simple_format(@post.content)
      .commentbox
        - if current_user
          = form_for [@post, @comment] do |f|
            = f.text_area :text, placeholder: "コメントしよう", class: "commentbox__text"
            = f.submit "送信", class: "commentbox__submit"
        - else
          %strong
            %p.commentbox__alert
              ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
        .commentbox__commentviewbox
          %h4.commentbox__commentviewbox__title
            = "<コメント一覧>"
            .commentbox__commentviewbox__title__comment
              - if @comments
                - @comments.each do |comment|
                  %p
                    = link_to "/users/#{comment.user_id}"  do
                      = comment.user.nickname
                    .commentbox__commentviewbox__title__comment__text
                      = simple_format(comment.text)

app/views/shared/_form.html.haml
= form_for @post do |f|
  = f.text_field :title, placeholder: "タイトル", class: "form__title"
  = f.collection_select :tag_ids, Tag.all, :id, :name, class: "form__select"
  = f.text_area :content, placeholder: "本文", class: "form__text"
  = f.submit "送信", class: "form__btn"

app/views/shared/_header.html.haml
.header
  .header__box
    = link_to "/", class: "header__box__logo" do
      = "Our wisdom bag"
    .header__box__right
      - if user_signed_in?
        = link_to "/users/#{current_user.id}", class: "header__box__right__user" do
          = current_user.nickname
        = link_to destroy_user_session_path, class: "header__box__right__logout", method: :delete do
          = "ログアウト"
      - else
        = link_to new_user_registration_path, class: "header__box__right__user" do
          = "新規登録"
        = link_to new_user_session_path, class: "header__box__right__logout" do
          = "ログイン"
      = link_to new_post_path do
        .header__box__right__new
          .header__box__right__new__btn
            = "投稿する" 

app/views/shared/_main.html.haml
.content__box__main
  = render @post
  = paginate(@post)

app/views/shared/_side.html.haml
.content__box__side
  .content__box__side__form
    .content__box__side__form__input-box
      = form_tag '/posts/search', method: :get do
        = text_field_tag :keyword
        = submit_tag "検索"
    .content__box__side__theme-box__theme
      = "テーマ"
    = render @tag
    
      

     

app/views/tags/_tag.html.haml
.content__box__side__theme-box__article-box
  = link_to "/tags/#{tag.id}", class: "content__box__side__theme-box__article-box__article" do
    = tag.name
  

app/views/tags/show.html.haml
.wrapper
  = render "shared/header"

  .content
    .content__box
      .content__username
        = @tag_name + "の記事"
      = render "shared/side"
      = render "shared/main"

app/views/users/_user.html.haml
.content__box__main__articlebox
  .content__box__main__articlebox__titlebox
    = link_to post_path(post.id), class:"content__box__main__articlebox__titlebox__title" do
      = post.title
  .content__box__main__articlebox__timebox
    .content__box__main__articlebox__timebox__time
      = post.created_at.strftime("%Y年%m月%d日 %H時%M分")
    .content__box__main__articlebox__timebox__good
      = "いいね"
  .content__box__main__articlebox__tag
    - post.tags.each do |tag|
      = tag.name

app/views/users/show.html.haml
.wrapper
  = render "shared/header"

  .content
    .content__box
      .content__username
        = @nickname + "さんの記事"
      = render "shared/side"
      = render "shared/main"